Emmisary presubmit
aws/eks-anywhere-prow-jobs pull request #183
Opened 2022-07-22 19:35 UTC by jonahjon

Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-22 19:37 UTC, jaxesn requested changes

2022-07-22 19:37 UTC, jaxesn commented on jobs/aws/eks-anywhere-build-tooling/emmisary-presubmitsyaml
> +    run_if_changed: "EKS_DISTRO_BASE_TAG_FILE|^build/lib/.*|Common.mk|projects/emmisary-ingress/emmisary/.*"
This tag file will be the python one

2022-07-22 19:43 UTC, abhay-krishna commented on jobs/aws/eks-anywhere-build-tooling/emmisary-presubmitsyaml
> +          value: projects/emmisary/emmisary
```suggestion
          value: projects/emissary-ingress/emissary
```

2022-07-22 19:44 UTC, abhay-krishna commented
`emmisary` -> `emissary` across the job definition and filename.

2022-07-22 19:45 UTC, jonahjon commented
> emissary

o yea good catch

2022-07-22 20:07 UTC, abhay-krishna approved these changes
/lgtm

2022-07-22 20:20 UTC, abhay-krishna commented
/approve

2022-07-23 00:55 UTC, jaxesn approved these changes
/approve

2022-07-23 00:56 UTC, merged